version: "3"

services:
  tomcat:
    build: 
      context: ./bin
    container_name: 'tomcat_mysql'
    privileged: true
    restart: 'always'
    ports:
      - "8088:8080"
    volumes: 
      - ./www:/opt/tomcat/apache-tomcat-8.5.57/webapps
    command: /usr/sbin/init
